"""add ip_address to monitor_data

Revision ID: 005
Revises: 001_initial
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_data', sa.Column('ip_address', sa.String(length=45), nullable=False, comment='服务器IP地址'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_data', 'ip_address')
    # ### end Alembic commands ###
